version: "3.8"
services:
  postgres:
    ports:
      - 5432:5432
    build:
      context: ./data/
      dockerfile: Dockerfile-postgres
    image: postgres-grupoa
    container_name: postgres-grupoa
    restart: on-failure

  springboot:
    ports:
      - 8080:8080
    build:
      context: ./backend/
      dockerfile: Dockerfile-springboot
    image: challenge-backend
    container_name: challenge-backend
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    ports:
      - 8090:80
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: challenge-frontend
    container_name: challenge-frontend
    depends_on:
      - springboot
    restart: on-failure
